apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: transientrolebindings.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            validUntil:
              type: string
            validFrom:
              type: string
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  names:
    kind: TransientRoleBinding
    plural: transientrolebindings
    singular: transientrolebinding
  scope: Namespaced
